steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu-west3-docker.pkg.dev/${PROJECT_ID}/fastapiv01/calculator-api:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'eu-west3-docker.pkg.dev/${PROJECT_ID}/fastapiv01/calculator-api:$SHORT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'calculator-api', '--image', 'europe-west1-docker.pkg.dev/$PROJECT_ID/fastapiv01/calculator-api:$SHORT_SHA', '--region', 'europe-west1']
options:
  logging: GCS_ONLY
   
