steps:
- name: 'gcr.io/cloud-builders/docker'
  id: build_docker_image
  args: [ 'build', '-t', 'eu-west3-docker.pkg.dev/${PROJECT_ID}/fastapiv01/calculator-api:$SHORT_SHA', '.' ]

- name: 'gcr.io/cloud-builders/docker'
  id: push_docker_image
  args: ['push', 'eu-west3-docker.pkg.dev/${PROJECT_ID}/fastapiv01/calculator-api:$SHORT_SHA']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'calculator-api', '--image', 'eu-west3-docker.pkg.dev/${PROJECT_ID}/fastapiv01/calculator-api:$SHORT_SHA', '--region', 'europe-west1']

options:
  logging: GCS_ONLY
